kraj/meta-openwrt

README.md
classes/openwrt.bbclass
conf/layer.conf
recipes-core/images/openwrt-juci-image.bb
recipes-core/juci/jucid/0001-main.c-define-_DEFAULT_SOURCE.patch
recipes-core/juci/jucid/0002-fix-makefile-in.patch
recipes-core/juci/jucid_git.bb

Needed to make a few changes to allow building the openwrt-juci-image.bb recipe using the yocto morty release of poky.

[meta-openwrt] Fixes to build openwrt-juci-image with morty release

---

recipes-core/ipset/ipset_6.24.bb
recipes-core/xtables-addons/xtables-addons_2.12.bb

- ipset does not need to inherit openwrt
- xtables-addons: INC_PR not needed
Signed-off-by: Aaron Brice <aaron.brice@datasoft.com>

Minor fixes to ipset and xtables-addons recipes

---

recipes-core/images/openwrt-base-image.bb

This patch removes the `inherit core-image image_types_uboot` line from the openwrt-base-image recipe, since the file has been merged into oe-core.

Remove reference to missing file image_types_uboot

---

README.md
classes/openwrt-distro-defaults.bbclass
classes/openwrt-kmods.bbclass
classes/openwrt-virtual-runtimes.bbclass
classes/openwrt.bbclass

Drop the conf/nodistro.conf that actually ends up being a distro
and document using INHERHIT += " openwrt-distro-defaults " in local.conf OR
an actual distro's conf.  Also prevent setting DISTRO_FEATURES to include
procd from overriding DISTRO_FEATURES and thereby losing the libc locale
config used with glibc (resulting in locale build failures).
Closes https://github.com/kraj/meta-openwrt/issues/30

distro: Be a better distro 'flavour' rather than distro

---

classes/openwrt-base-files.bbclass
classes/openwrt.bbclass
recipes-core/firewall3/firewall3_git.bb
recipes-core/netifd/netifd_git.bb
recipes-core/procd/procd_git.bb
recipes-core/rpcd/rpcd_git.bb
recipes-core/uci/uci_git.bb
recipes-core/uhttpd/uhttpd_git.bb
recipes-extended/mountd/mountd_git.bb
recipes-tweaks/base-files/base-files-openwrt/0001-use-sh-not-ash.patch
recipes-tweaks/base-files/base-files-scripts.bb
recipes-tweaks/base-files/base-files_3.%.bbappend
recipes-tweaks/dnsmasq/dnsmasq_%.bbappend
recipes-tweaks/hostapd/hostapd_%.bbappend

Recipes pulling scripts and configs from openwrt.git were not
indicating the GPL-2.0+ license on that repo.  Therefore add
the LICENSE file from openwrt.git and update LICENSE with an
'&GPL-2.0+'.  Since this is primarily initscripts and such,
while most of the actual software (like procd, ubus) etc is
under an MIT, BSD, or Apache license, it may be desirable to
replace the scripts with MIT, BSD, or Apache scripts.
Closes https://github.com/kraj/meta-openwrt/issues/43

tree-wide: Include Openwrt license when pulling from openwrt repo

---

recipes-core/firewall3/firewall3_git.bb

On top of the previous odhcpd/odhcpc6c PR this gets firewall3 working for both ipv4 and ipv6 by adding RRECOMMENDS on the kernel modules and adding module loading configuration.

This adds the necessary netfilter/xtables kernel modules for firewall3

---

recipes-core/odhcp6c/odhcp6c_git.bb
recipes-core/odhcpd/odhcpd/0100-OE-build-fails-due-to-libnl-tiny-dependency-in-CMakeLists.patch
recipes-core/odhcpd/odhcpd_git.bb
recipes-core/packagegroups/packagegroup-openwrt-minimal.bb
recipes-extended/packagegroups/packagegroup-openwrt-base.bb

odhcpd is the default DHCPv6(-PD)/RA server and relay in openwrt-core, so add it to openwrt-minimal.  Also make sure it works by having dnsmasq be sure to ship /etc/config/dhcp (which odhcpd also relies on; seems a bit excessive to make this single file a common package though).

Add v6 odhcpd and dhcp6c which are now part of openwrt base upstream

---

recipes-core/iwinfo/iwinfo_git.bb

splitting this out from the styleguide series.   Prevents intermittent build failures on iwinfo with BitBake 1.34 due to parallel make failing.

iwinfo doesn't like parallel builds, so don't

---

recipes-extended/luci/luci/cmake.patch
recipes-extended/luci/luci_git.bb

The first patch fixes the hard-coded path in uhttpd so that it matches the default path for profile and initscripts so that luci finds the same binaries when there are two binaries of the same name in two different locations.
The second patch fixes the CMake created for building luci and the recipe for luci so that luci-bwc is built and installed in the correct location so that realtime graphs display activity.

Luci: Fix "realtime graphs displaying no data"

---

recipes-core/jsonpath/jsonpath_git.bb

It's a BSD-1-Clause not generic 'BSD'
Closes https://github.com/kraj/meta-openwrt/issues/58

jsonpath: Indicate correct license

---

recipes-core/netifd/netifd/200-buffer-overflow-fix.patch

Improve patch based on upstream feedback, and add a fix
for vlan on top of bridge in another file that is needed
as a result of this patch.

netid: Update buffer overrun patch based on upstream feedback

---

recipes-tweaks/busybox/busybox/fragment-noifupdown.cfg

Newest busybox splits ifupdown into ifup and ifdown configuration
options.  This means we need to update the fragment that turns off
ifup/ifdown so that it doesn't interfere with netifd

busybox: Fix no-ifupdown for busybox 1.27

---

recipes-tweaks/base-files/base-files-scripts.bb
recipes-tweaks/base-files/base-files_3.%.bbappend
recipes-tweaks/busybox/busybox_1.27%.bbappend

This is some initial PACKAGECONFIG work to allow to choose a more openwrt-like image, a neutral (the default) which has some openwrt-specific things, but is not as close to upstream openwrt, and more oe-based (more for picking out specific packages from meta-openwrt without requiring too much from openwrt just to do that).

Initial support for more openwrt, more oe, or neutral flavours of meta-openwrt

---

classes/openwrt-lua.bbclass
recipes-core/libubox/libubox_git.bb
recipes-core/netifd/netifd_git.bb
recipes-core/ustream-ssl/ustream-ssl_git.bb
recipes-extended/mountd/mountd_git.bb

Contains changes to build openwrt-image-minimal and openwrt-image-base, if the ${libdir} is other than 
/usr/lib/.
Regards,
Jagadeesh

Replace hardcoded 'lib' string with a generic value

---

recipes-tweaks/iptables/iptables/600-shared-libext.patch

Adapt the existing patch for enable shared iptables
library for version 1.6.2
Signed-off-by: Parthiban Nallathambi <pn@denx.de>

[iptables]: Adapt patch for 1.6.2 version

---

recipes-core/netifd/netifd_git.bb

Removing with "rm -rf ${D}/lib" drops all the necessary files
for 32 bit target. This is applicable only if the target is 64bit.
Copying with care using ${base_libdir} is fixes the problem.
Removing is not necessary.
Signed-off-by: Parthiban Nallathambi <pn@denx.de>

rm /lib drops all the needed files for 32bit targets

---

recipes-core/netifd/netifd/0001-resolv.conf.auto-Use-run-instead-of-tmp.patch
recipes-core/netifd/netifd_git.bb

Using netifd as network manager along with systemd provokes the bad usage
of path, in this case /tmp/. All the runtime configuration needs to be
sotored as part of /run
Problem:
========
assuming: ln -fs /tmp/resolv.conf.auto /etc/resolv.conf
If any application tend to use Filesystem namespace to have separate /tmp and
try to use DNS resolution from netifd, it will not be able to resolve the path/symlink.
Usage of PrivateTmp=yes:
------------------------
For example, systemd-timesyncd.service in systemd uses the option "PrivateTmp=yes"
in the service file to have separate /tmp filesystem namespace and uses glibc
getaddrinfo for name resolution, which in turm follows the symlink to /tmp which
doesn't exit in new namespace
So moving the runtime configuration to /run here
Signed-off-by: …

Use /run instead of /tmp

---

recipes-extended/luci/luci_git.bb

The libraries is installed to /lib make luci doesn't work correctly.

luci: install library to /usr/lib

---

recipes-tweaks/iptables/iptables_1.6%.bbappend

Fix the arguments of the do_split_packages function, to look
in the correct place for files, and also use prepend=True
so the different module packages look for matching files before
$PN, provide a better solution avoiding RDEPENDS_remove.
Signed-off-by: Alejandro Hernandez <aehs29@gmail.com>

iptables: call split packages correctly

---

recipes-core/xtables-addons/xtables-addons_3.3.bb

Can't fetch https://fossies.org/linux/privat/xtables-addons-3.2.tar.xz. Bump to 3.3.

Version Bump to xtables-addons-3.3. Old URL broken.

---

recipes-core/rpcd/rpcd_git.bb

Relevant trimmed build error:
```
in function `rpc_login_test_password':
/usr/src/debug/rpcd/git-r0/git/session.c:823: undefined reference to `crypt'
```

Can't compile rpcd. Missing crypt library.

---

classes/openwrt-kmods.bbclass

If the deploy and tmp directories were zapped but the sstate-cache
retained, it could happen that openwrt_flatten_modules_hook was run
without ${STAGING_KERNEL_BUILDDIR} ever being populated.  Add an
explicit dependency to fix that.  Also add a check that something
was actually read from the kernel-abiversion file.

classes/kmods: assure kernel-abiversion exists

---

recipes-extended/luci/luci_git.bb
recipes-networking/uhttpd/uhttpd_git.bb

**ERROR**
`
Nothing PROVIDES 'libxcrypt' (but /media/cbueno/DATA/yocto/b2open-training/poky-gatesgarth/meta-openwrt/recipes-networking/uhttpd/uhttpd_git.bb, /media/cbueno/DATA/yocto/b2open-training/poky-gatesgarth/meta-openwrt/recipes-extended/luci/luci_git.bb DEPENDS on or otherwise requires it)
libxcrypt was skipped: PREFERRED_PROVIDER_virtual/crypt set to musl, not libxcrypt
`
Change libxcrypt by variable virtual/crypt.
Branch tested: **gatesgarth**
Tested with MACHINES: **raspberrypi4**

Fix and replace libxcrypt (branch master with toolchain MUSL)

---

recipes-extended/luci/luci_git.bb
recipes-networking/uhttpd/uhttpd_git.bb
recipes-networking/umdnsd/umdnsd_git.bb

Fixed error when compile umdnsd with branch **master** 
Tested with: MACHINE **raspberrypi4**
-------------------------------------------------------------
meta-openwrt/recipes-networking/umdnsd/umdnsd_git.bb
**ERROR**
`
|  /ssdext/yocto/poky-gatesgarth/build-openwrt/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-musleabi/umdnsd/git-r0/git/util.h:22:19: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type 'time_t' {aka 'long long int'} [-Werror=format=]
|    22 |   fprintf(stderr, "mdnsd: %s (%d): " fmt, __func__, __LINE__, ## __VA_ARGS__); \
`
**FIXED:** umdns: fix 64-bit time format string
https://git.openwrt.org/?p=project/mdnsd.git;a=commit;h=78aa36b0e9808e801c527c6dc47320e593309522

Update SRCREV in umdnsd to correct compilation error 

---

recipes-extended/mountd/mountd_git.bb

Simplify the sed run to consider only -Werror: this also fixes it
as it cannot find any instances of "-Werror --std=gnu99" (or not all
are found, resulting in a build error).

netifd: Fix build

---

recipes-core/make-ext4fs/make-ext4fs_git.bb

Add space to TARGET_CFLAGS_append to fix error:
| aarch64-somainline-linux-gcc: error: unrecognized command line option '-fno-trapping-math-Wno-implicit-function-declaration'; did you mean '--warn-no-implicit-function-declaration'?

core: make-ext4fs: Fix TARGET_CFLAGS

---

recipes-core/rpcd/rpcd_git.bb

Install the unauthenticated.json file to /usr/share/rpcd/acl.d/
to fix a NetworkError issue at login, preventing unauthenticated
users to... authenticate.

core: rpcd: Fix LuCI authentication issue

---

recipes-extended/luci/luci/cmake.patch

The autogenerated plural_formula.c file was not included in the
parser.so library: add it to the mix by setting the file as autogenerated
and including it to the shared parser.so library.
This fixes a complain for pluralParseAlloc being an undefined symbol,
since that's where this function is defined (and others as well).

extended: luci: cmake: Fix missing plural_formula.c in build

---

recipes-extended/liblucihttp/liblucihttp_git.bb

OpenWrt requires liblucihttp-lua to be enabled

liblucihttp enable liblucihttp-lua

---

recipes-core/make-ext4fs/make-ext4fs_git.bb
recipes-core/procd/procd-inittab.bb

`GPL-2.0` license file name in `hardknott` is changed to `GPL-2.0-only`
added a space in compiler flags

fix various build errors: GPL-2.0 license name, compiler flags

---

recipes-core/iwinfo/iwinfo_git.bb

Without the iwinfo shared library installed as `libiwinfo.so.0`, none of the `iwinfo` command line tool, the lua plugin or the rpcd plugin will work.

iwinfo: Install shared library with correct filename
